### ISSUE TITLE
Task 01 -- Create GitHub account and clone some repositories

### ISSUE THREAD

**Issue by dudung** [dudung/sk5003-02-2022-2#1]
+ Attending first session on Saturday, 11 March 2023, 07.00 using Zoom [95582806117](https://itb-ac-id.zoom.us/j/95582806117?pwd=dFprT1FiNUwrZHBONmcyR3hHL29xZz09).
+ Create new GitHub account [here](https://github.com/signup).
+ For backup course materials and communication [fork this repository](https://github.com/dudung/sk5003-02-2022-2/fork).
+ Navigate to repository `py-jupyter-nb` and [fork it](https://github.com/dudung/py-jupyter-nb/fork).
+ Navigate to repository `python` and [fork it](https://github.com/dudung/python/fork).
+ Report link of your GitHub user page below. Just put a single line of that link followed by a line of your name, e.g.
  > https://github.com/dudung
  > Sparisoma Viridi

**Comment by zains2itbdatascience** [comment]
https://github.com/zains2itbdatascience

**Comment by aliefpascal** [comment]
https://github.com/aliefpascal

**Comment by moestika** [comment]
https://github.com/moestika

**Comment by zakyerdiansyah** [comment]
https://github.com/zakyerdiansyah

**Comment by tororahmanz** [comment]
https://github.com/tororahmanz

**Comment by listynirmala** [comment]
https://github.com/listynirmala
an Listyani Nirmalasari

**Comment by Yaksuwa** [comment]
https://github.com/Yaksuwa
an Yandika Restu Wara

**Comment by aad169** [comment]
https://github.com/aad169
an Ahmad Mushawir

**Comment by eidelbert** [comment]
https://github.com/eidelbert

an Eidelbert Suherianto Sinaga

**Comment by nilampuspita** [comment]
https://github.com/nilampuspita
an Dyah Puspita Sari Nilam Utami

**Comment by RizkiNovitriPutri** [comment]
https://github.com/rizkinovitriputri

an Rizki Novitri Susanti Setia Putri

**Comment by galiharisona** [comment]
https://github.com/galiharisona
an Galih Arisona

**Comment by inassuha** [comment]
https://github.com/inassuha

an Inas Suha Lailah Qodriyah

**Comment by ghafuraws** [comment]
https://github.com/ghafuraws

an Muhammad Ghafur

**Comment by antons1102** [comment]
an Anton Sujarwo

**Comment by adityaadiaksa** [comment]
https://github.com/adityaadiaksa

A/n Aditya Adiaksa

**Comment by zuhrirachman** [comment]
https://github.com/zuhrirachman
a.n. Zuhri Arieffasa Suffaturrachman

**Comment by SatrioYolandanu** [comment]
https://github.com/SatrioYolandanu
a.n Satrio Yolandanu

**Comment by veralaksa** [comment]
https://github.com/veralaksa

a.n Vera Elysa Risti

**Comment by titobagasw** [comment]
https://github.com/titobagasw

a.n. Tito Bagaswara

**Comment by Andinikma19** [comment]
https://github.com/Andinikma19
a.n Andi Nikma Srihandayani

**Comment by dwy-prasat** [comment]
https://github.com/dwy-prasat
a.n Dwi Putra Prasatya

**Comment by afinsani** [comment]
https://github.com/afinsani

an Akhmad Faeda Insani-20922313
