### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dudung** [dudung/sk5003-02-2022-2#2]
+ You can put your question here.
+ Write it in English or Indonesian.
+ Thank you. Let's communicate.

**Comment by aliefpascal** [comment]
pak, saya belum bisa absen di six karena tidak ada kelas yang tersedia di six aja

**Comment by aliefpascal** [comment]
oh iya pak, mohon izin informasikan rekan saya atas nama Akhmad Faeda Insani belum bisa hadir kuliah, beliau info saya karena sedang menjalani ibadah umroh pak.

**Comment by dudung** [comment]
Terima kasih atas informasinya, Pak @aliefpascal.

**Comment by SatrioYolandanu** [comment]
maaf pak, untuk perkuliahan tanggal 8 di six absen saya masuk, cuman untuk di edunex terisi tidak absen, mohon bantuanya pak dudung

**Comment by aliefpascal** [comment]
saya pun mengalami hal yang sama pak Dudung seperti mas @SatrioYolandanu .
Terima kasih pak

**Comment by dudung** [comment]
Terima kasih telah menginformasikan, Pak @SatrioYolandanu dan Pak @aliefpascal.

**Comment by antons1102** [comment]
Assalamualaikum Pak, ijin menanyakan terkait presensi atas nama Anton Sujarwo - 20922326 di akademik hanya 87,5% sedangkan untuk perkuliahan selalu hadir. Kemungkinan saya lupa menandai hadir pada saat perkuliahan berlangsung. Mohon arahannya Pak, Terimakasih

**Comment by dudung** [comment]
Waalaikumsalam wr wb, Pak @antons1102. Apakah ada perkiraan kapan sajalupa mengisi kehadirannya, Pak? Terima kasih.

**Comment by antons1102** [comment]
> Waalaikumsalam wr wb, Pak @antons1102. Apakah ada perkiraan kapan sajalupa mengisi kehadirannya, Pak? Terima kasih.

Sepertinya di minggu-minggu akhir Pak, karena seinget saya bulan lalu saya cek presensi tidak ada yg bolong.
Saya coba cek di akademik tidak terlihat kelas mana yang saya lupa menandai hadir.

Terimakasih
