### ISSUE TITLE
Tidak dapat Absen di Aplikasi SIX

### ISSUE THREAD

**Issue by eidelbert** [dudung/sk5003-02-2022-2#4]
Pagi Pak,
Izin menyampaikan saya belum bisa absen perkuliahan Pemrograman dalam Sains di aplikasi SIX, karena perkuliahan ini belum muncul di kalender jadwal perkuliahan mahasisa saya.
Nama : Eidelbert Suherianto Sinaga
NIM : 20922309
<img width="1177" alt="Screenshot 2023-03-18 at 07 28 13" src="https://user-images.githubusercontent.com/4254572/226078326-49e7128a-3381-4409-b5cb-cb62146d4e35.png">

Terimakasih

**Comment by dudung** [comment]
Terima kasih telah mengabari, Pak @eidelbert. Akan disisipkan dengan fitur sit-in.

**Comment by eidelbert** [comment]
Baik Pak Dudung, makasih Pak.

**Comment by zuhrirachman** [comment]
Izin menyampaikan, Pak. Saya kelupaan untuk masuk tanda hadir di pertemuan hari ini, Sabtu, 1 April 2023. Terima kasih.
Nama: Zuhri Arieffasa Suffaturrachman
NIP: 20922310

**Comment by RizkiNovitriPutri** [comment]
izin pak saya atas nama Rizki Novitri NIM 20922314 lupa absen tanggal 01 April 2023 
Terimakasih sebelumnya pak.

**Comment by aad169** [comment]
Saya tadi lupa absen pak, untuk tanggal 1 April 2023
Nama : Ahmad Mushawir
NIM: 20922307

Terimakasih pak

**Comment by adityaadiaksa** [comment]
Izin pak saya atas nama Aditya Adiaksa NIM 20922320 lupa absen tanggal 01 April 2023
Terimakasih banyak pak

**Comment by dudung** [comment]
Sudah diisikan kehdirannya, Pak @zuhrirachman, Bu @RizkiNovitriPutri, Pak @aad169, dan Pak @adityaadiaksa.

**Comment by zuhrirachman** [comment]
> Sudah diisikan kehdirannya, Pak @zuhrirachman, Bu @RizkiNovitriPutri, Pak @aad169, dan Pak @adityaadiaksa.

Terima kasih, Pak Dudung.

**Comment by veralaksa** [comment]
Selamat sore pak Dudung,
Mohon Maaf pak sebelumnya..
Dengan Vera elysa - 20922317 ..
Ijin menyampaikan kendala terkait Edunex pak.
Selama ini saat presensi saya masih menggunakan account calon mahasiswa (maaf atas ketidaktauan sy),
hari ini sy baru login dengan account INA yang seharusnya, sehingga ketika saya login,  presensi saya selama perkuliahan yg telah sy ikuti dan sy tandai hadir sebelumnya saat ini menjadi 0% diaccount yang baru,

berikut tampilan dihalaman saya pak.
<img width="741" alt="Presensi Vera Elysa Risti" src="https://user-images.githubusercontent.com/127570258/229469472-4906a906-a50e-40f7-a143-e4b205856570.png">

demikian disampaikan mohon bantuannya pak,
Terima kasih

Salam,
Vera elysa

**Comment by dudung** [comment]
Bu @veralaksa, dapat ditampilkan screenshot akun calon mahasiswanya, yang menandakan selama ini hadir?

**Comment by adityaadiaksa** [comment]
Izin pak saya atas nama Aditya Adiaksa NIM 20922320 lupa absen tanggal 08 April 2023
Terimakasih banyak pak

**Comment by dudung** [comment]
Sudah disikan, Pak @adityaadiaksa. Terima kasih telah melaporkannya.

**Comment by SatrioYolandanu** [comment]
maaf pak, untuk perkuliahan tanggal 8 di six absen saya masuk, cuman untuk di edunex terisi tidak absen, mohon bantuanya pak dudung

**Comment by dudung** [comment]
> maaf pak, untuk perkuliahan tanggal 8 di six absen saya masuk, cuman untuk di edunex terisi tidak absen, mohon bantuanya pak dudung

Pertemuan tersebut tidak bisa karena saat itu kelihatannya Edunexnya belum dibuat, Pak. Presensi akan dilihat dari SIX, Pak @SatrioYolandanu . Tidak apa-apa.
