### ISSUE TITLE
Kuliah 1 April 2023 -- 0730

### ISSUE THREAD

**Issue by dudung** [dudung/sk5003-02-2022-2#5]
Rekan-rekan Ysh., perkuliahan hari ini dimulai sekitar 0730. Terima kasih.

**Comment by zuhrirachman** [comment]
Baik, Pak Dudung. Terima kasih atas informasinya..

**Comment by dudung** [comment]
4. **Pemecahan masalah sederhana dan ilustrasinya dengan Python** \
`slide` [10.5281/zenodo.7790482](https://doi.org/10.5281/zenodo.7790482) \
`video` [Y0fqcq6w7gg](https://youtu.be/Y0fqcq6w7gg) \
`tugas` -
