### ISSUE TITLE
Kuliah 8 April 2023

### ISSUE THREAD

**Issue by dudung** [dudung/sk5003-02-2022-2#6]
**Python: Import, function, class** \
`slide` [10.5281/zenodo.7809396](https://doi.org/10.5281/zenodo.7809396) \
`video` [](https://youtu.be/) \
`tugas` - \
`ednex` https://edunex.itb.ac.id/courses/48923/preview/164315

+ Silakan menyampaikan hal-hal yang diperlukan untuk kuliah hari ini di sini, seperti pertanyaan, diskusi, saran, kritik, dan lain-lain. Terima kasih.

**Comment by moestika** [comment]
Maaf pak saya mau bertanya,
Kita bisa membuat variabel dictionary di dalam file Python. Nah apabila kita mempunyai data yang lumayan banyak (misalnya 1000 data ke atas), jika dibandingkan dengan membuat database lebih efisien yang mana ya pak kalau dari segi performa dan ukuran filenya?

Terima kasih.

**Comment by dudung** [comment]
+ Database baik untuk hal-hal yang akan sering diupdate sedangkan dictionary lebih tepat untuk sesuatu yang cenderung tetap untuk jangka waktu pendek.
+ Database merupakan data yang tersimpan, sedangkan dictionary lebih tepat digunakan sebagai definisi dari obyek-obyek yang tersimpan dalam database.
+ Pendapat yang ada juga cenderung relatif, seperti di [sini](https://softwareengineering.stackexchange.com/questions/129043/what-are-the-relative-advantages-of-dictionaries-versus-databases).

**Comment by moestika** [comment]
> + Database baik untuk hal-hal yang akan sering diupdate sedangkan dictionary lebih tepat untuk sesuatu yang cenderung tetap untuk jangka waktu pendek.
> + Database merupakan data yang tersimpan, sedangkan dictionary lebih tepat digunakan sebagai definisi dari obyek-obyek yang tersimpan dalam database.
> + Pendapat yang ada juga cenderung relatif, seperti di [sini](https://softwareengineering.stackexchange.com/questions/129043/what-are-the-relative-advantages-of-dictionaries-versus-databases).
> + Semoga cukup memberikan gambaran untuk pencarian lebih lanjut ya, Pak @moestika. Terima kasih.

Baik siap pak @dudung, terima kasih atas pencerahannya.
