### ISSUE TITLE
Task 03 -- Ide permasalahan untuk diselesaikan

### ISSUE THREAD

**Issue by dudung** [dudung/sk5003-02-2022-2#8]
+ Simpan jawaban dalam berkas PDF dan diunggah di sini dan di [Edunex](https://edunex.itb.ac.id/courses/48923/preview/168407/72782).
+ Usulkan ide suatu permasalahan yang akan dipecahkan, dapat merupakan embrio untuk tesis, permasalahan di tempat kerja, atau hal yang menarik Anda.
+ Sertakan konsep-konsep apa, yang selama ini telah diberikan di kuliah ini, yang perlu Anda gunakan.
+ Terkait dengan konsep-konsep tersebut cantumkan minggu perkuliahannya (1-7) yang dapat disajikan dalam bentuk tabel.
+ Bila diperlukan cantumkan pula konsep-konsep lain yang diperlukan, tetapi belum diberikan dalam kuliah ini, disertai dengan referensinya.

**Comment by antons1102** [comment]
[IDE PERMASALAHAN UNTUK DISELESAIKAN.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11413984/IDE.PERMASALAHAN.UNTUK.DISELESAIKAN.pdf)

Ide Permasalahan untuk diselesaikan : 
20922326 - ANTON SUJARWO

**Comment by galiharisona** [comment]
Berikut terlampir
20922325_GalihArisona

[Tugas III Ide Permasalahan Untuk Diselesaikan_20922325_GalihArisona.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11418104/Tugas.III.Ide.Permasalahan.Untuk.Diselesaikan_20922325_GalihArisona.pdf)

**Comment by aliefpascal** [comment]
[Tugas 3-20922321_AliefPascalTaruna.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11418121/Tugas.3-20922321_AliefPascalTaruna.pdf)

Ide Permasalahan untuk diselesaikan :
20922321-AliefPascalTaruna

**Comment by aad169** [comment]
Nama: Ahmad Mushawir
NIM: 20922307

Dear Pak Dudung, terlampir Ide Permasalahan untuk diselesaikan.
Terima kasih.

[Ahmad Mushawir - Tugas 3 SK5003.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11419284/Ahmad.Mushawir.-.Tugas.3.SK5003.pdf)

**Comment by afinsani** [comment]
Dear Pak Dudung 


AKHMAD FAEDA INSANI-20922313
terlampir disampaikan tugas ide permasalahan untuk diselesaikan



[Tugas 4_Akhmad Faeda Insani_20922313.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11428718/Tugas.4_Akhmad.Faeda.Insani_20922313.pdf)


Terima Kasih

**Comment by Yaksuwa** [comment]
Dear Pak @dudung 

Berikut disampaikan Task 03 -- Ide permasalahan untuk diselesaikan #8
[Tugas.III.Ide.Permasalahan.Untuk.Diselesaikan_20922306_YandikaRestuWara.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11437715/Tugas.III.Ide.Permasalahan.Untuk.Diselesaikan_20922306_YandikaRestuWara.pdf)
Terima Kasih

**Comment by moestika** [comment]
Dear Pak @dudung,

Berikut terlampir ide permasalahan yang akan diselesaikan dari saya. Mohon untuk koreksinya apabila terdapat bagian-bagian yang belum sesuai.

Atas perhatian dan kerja samanya saya ucapkan terima kasih.

[
[Ide Permasalahan untuk Diselesaikan.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11438239/Ide.Permasalahan.untuk.Diselesaikan.pdf)
](url)

**Comment by veralaksa** [comment]
dengan hormat,

bersama ini terlampir tugas submit ide permasalahan untuk diselesaikan :
nama : Vera Elysa Risti
Nim   : 20922317

File    : 
[20922317_VERA ELYSA RISTI_Ide.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11438265/20922317_VERA.ELYSA.RISTI_Ide.pdf)

demikian disampaikan, terima kasih

**Comment by eidelbert** [comment]
Dear Pak @dudung ,
Terlampir ide permasalahan yang diusulkan.
[Tugas III - 20922309 - Eidelbert Suherianto Sinaga.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11442699/Tugas.III.-.20922309.-.Eidelbert.Suherianto.Sinaga.pdf)

Demikian disampaikan, terima kasih.
Best Regards,
Eidelbert Suherianto Sinaga
20922309

**Comment by dwy-prasat** [comment]
Dear Pak @dudung ,
Terlampir ide permasalahan yang untuk diselesaikan.

[Tugas 3_20922312_Dwi Putra Prasatya.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11446841/Tugas.3_20922312_Dwi.Putra.Prasatya.pdf)

Nama : Dwi Putra Prasatya
NIM : 20922312

Terimakasih

**Comment by tororahmanz** [comment]
Dear Pak Dudung

terlampir disampaikan tugas ide permasalahan untuk diselesaikan
TORO RAHMAN AZIZ - 20922322
[Tugas Ide Permasalahan - Toro Rahman Aziz.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11447210/Tugas.Ide.Permasalahan.-.Toro.Rahman.Aziz.pdf)

Demikian disampaikan, terima kasih.

**Comment by zains2itbdatascience** [comment]
Dear Pak Dudung,

Terlampir disampaikan tugas ide permasalahan di unit kerja untuk diselesaikan.
ZAINUDDIN - 20922319

[Tugas Ide Permasalahan - Zainuddin.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11447686/Tugas.Ide.Permasalahan.-.Zainuddin.pdf)

Demikian disampaikan, terima kasih.

**Comment by nilampuspita** [comment]
Dear Pak Dudung

terlampir disampaikan tugas ide permasalahan untuk diselesaikan
DYAH PUSPITA SARI NILAM UTAMI_20922327
[Tugas 3_20922327_Dyah Puspita Sari Nilam Utami.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11450039/Tugas.3_20922327_Dyah.Puspita.Sari.Nilam.Utami.pdf)

Demikian disampaikan, terima kasih

**Comment by listynirmala** [comment]
Dear Pak Dudung,


Terlampir disampaikan Tugas Konsep/Ide Permasalahan untuk diselesaikan.
Atas nama Listyani Nirmalasari_20922324
[Tugas3-20922324-Listyani Nirmalasari .pdf](https://github.com/dudung/sk5003-02-2022-2/files/11450988/Tugas3-20922324-Listyani.Nirmalasari.pdf)

Demikian disampaikan, terima kasih.

**Comment by zakyerdiansyah** [comment]
Dear pak dudung, 

Terlampir tugas konsep/ide permasalahan untuk diselesaikan
Muhammad Zaky Erdiansyah_20922305
[20922305 ZAKY IDE PERMASALAHAN.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11458481/20922305.ZAKY.IDE.PERMASALAHAN.pdf)

Demikian disampaikan, terima kasih

**Comment by ghafuraws** [comment]
Dear Pak Dudung,

Terlampir tugas konsep/ide permasalahan untuk diselesaikan
Muhammad Ghafur Abdulah_20922308
[Tugas 3 - Ide Permasalahan - 20922308 - Muhammad Ghafur.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11458550/Tugas.3.-.Ide.Permasalahan.-.20922308.-.Muhammad.Ghafur.pdf)

Demikian disampaikan, terima kasih

**Comment by adityaadiaksa** [comment]
Dear Pak Dudung, 

Nama: Aditya Adiaksa
NIM: 20922320

Terlampir Tugas Konsep atau Ide Permasalahan untuk diselesaikan.

Terima kasih.
[Tugas Ide Permasalahan 20922320 Aditya Adiaksa SK 5003.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11459476/Tugas.Ide.Permasalahan.20922320.Aditya.Adiaksa.SK.5003.pdf)

**Comment by Andinikma19** [comment]
Dear Pak Dudung, 

Terlampir tugas konsep/ide permasalahan untuk diselesaiakan mahasiswa :  
Nama : Andi Nikma Srihandayani
NIM : 20922311

[TUGAS SK5003_Andi Nikma Srihandayani.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11461732/TUGAS.SK5003_Andi.Nikma.Srihandayani.pdf)

Terima kasih.

**Comment by zuhrirachman** [comment]
Kepada Yth.
Dr, rer. nat. Sparisoma Viridi, S.Si.

Bersama ini, saya
Nama : Zuhri Arieffasa Suffaturrachman
NIM : 20922310
melampirkan Tugas I mengenai Desain Embrio Tesis pada link berikut.

[Tugas I Programming in Science_20922310_Zuhri A. Suffaturrachman.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11467536/Tugas.I.Programming.in.Science_20922310_Zuhri.A.Suffaturrachman.pdf)

Terima kasih.

**Comment by inassuha** [comment]
Assalaamu'alaikum, berikut saya lampirkan tugas mengenai ide permasalahan dengan rencana konsepnya
Nama : Inas Suha LQ
NIM   : 20922318

[TASK 03 PEMROGRAMAN DALAM SAINS - INAS SUHA LQ.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11468089/TASK.03.PEMROGRAMAN.DALAM.SAINS.-.INAS.SUHA.LQ.pdf)

Trimakasih

**Comment by RizkiNovitriPutri** [comment]
Dengan Hormat Pa Dudung,

Berikut disampaikan tugas ide permasalahan 
Nama : Rizki Novitri Susanti Setia Putri
NIM : 20922314

[Ide Permasalahan _ Rizki Novitri 20922314.pdf](https://github.com/dudung/sk5003-02-2022-2/files/11468220/Ide.Permasalahan._.Rizki.Novitri.20922314.pdf)

Terimakasih

**Comment by dudung** [comment]
Terima kasih, telah mengumpulkan tugas, Ibu dan Bapak: @antons1102, @galiharisona, @aliefpascal, @aad169, @afinsani, @Yaksuwa, @moestika, @veralaksa, @eidelbert, @dwy-prasat, @tororahmanz, @zains2itbdatascience, @nilampuspita, @listynirmala, @zakyerdiansyah, @ghafuraws, @adityaadiaksa, @SatrioYolandanu, @Andinikma19, @zuhrirachman, @inassuha, @RizkiNovitriPutri.

Dengan demikian issue ini ditutup.
